import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const jost = localFont({
  src: "./../assets/fonts/jost-variable.ttf",
  variable: "--jost",
  weight: "100 200 300 400 500 600 700 800 900",
});

const roboto = localFont({
  src: "./../assets/fonts/KFOmCnqEu92Fr1Mu4mxK (1).ttf",
  variable: "--roboto",
  // weight: "100 900",
});
const robotoMedium = localFont({
  src: "./../assets/fonts/KFOlCnqEu92Fr1MmEU9fBBc4 (1).ttf",
  variable: "--roboto-medium",
  // weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jost.variable} ${roboto.variable} ${robotoMedium.variable}`}>
        {children}
      </body>
    </html>
  );
}
